// La barre laterale enseignant n'est definie que hors build public, sinon
// Docusaurus echouerait a generer une barre pointant vers des fichiers exclus.
const PUBLIC_BUILD = process.env.PUBLIC_BUILD === '1';

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  tpSidebar: [
    'intro',
    {
      type: 'autogenerated',
      dirName: 'chantiers',
    },
  ],
  ...(PUBLIC_BUILD
    ? {}
    : {
        enseignantSidebar: [
          {
            type: 'autogenerated',
            dirName: 'enseignant',
          },
        ],
      }),
};

module.exports = sidebars;
